const Home = () => {
  return <div className="bg-white text-red-500 overflow-y-auto flex flex-col h-full pb-10">Home Page
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et vehicula nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque accumsan a velit in viverra. Cras urna mauris, pellentesque id aliquam eu, condimentum non lacus. Nam viverra leo eu neque placerat, porttitor imperdiet neque vehicula. Nullam eget diam non erat varius gravida eget eu dui. Nam eleifend nunc neque, vitae sollicitudin purus accumsan quis. Nullam pretium viverra risus, nec porta est placerat ac. Vestibulum tincidunt magna nec enim lobortis, ac vulputate justo sollicitudin. Suspendisse aliquam nunc non libero suscipit, a bibendum magna molestie. Mauris malesuada facilisis egestas. Phasellus eget fringilla turpis, eleifend pulvinar ex. Praesent dui nibh, accumsan ac vestibulum eget, fringilla ut augue. Nam quam eros, aliquam non nunc at, pretium cursus diam. Sed pharetra ante at risus dignissim cursus. Maecenas aliquet sapien a orci consectetur, a cursus libero accumsan.

Sed tristique consequat turpis luctus ultricies. Donec auctor ullamcorper neque. Etiam sed rutrum diam, tincidunt consectetur elit. Sed quis dolor congue, sodales ante placerat, laoreet libero. Vivamus vel ornare magna, et pretium sapien. Nulla aliquam mattis tortor, ac interdum mi fringilla in. Nam sit amet commodo tellus. Proin condimentum dignissim eros eget tempus.

Curabitur ut aliquam massa. Aliquam in metus aliquam, interdum tortor sit amet, varius augue. Maecenas egestas mauris nec nulla vestibulum euismod. Sed in orci consectetur, luctus dolor a, finibus diam. Integer congue risus vitae cursus varius. Suspendisse nec mollis quam, in porttitor lectus. Aliquam et laoreet orci. Sed tincidunt magna in mi vulputate iaculis. Aliquam sit amet velit ac urna laoreet varius a quis nunc. Nam sed pellentesque mauris. Morbi vel ligula at dolor dapibus tincidunt. Nullam sit amet interdum elit, vel commodo ipsum. Phasellus dapibus nisi vitae volutpat luctus. Ut accumsan pretium ligula, at malesuada risus maximus at.

Donec a est pellentesque libero congue elementum. Donec consectetur justo et sem maximus, ut condimentum nisl laoreet. Morbi ac enim in enim volutpat suscipit. Donec ultrices convallis orci eget accumsan. Ut bibendum ante et massa malesuada, a consequat dolor luctus. Curabitur nulla nisl, sodales nec dictum a, feugiat at ante. Nunc volutpat luctus ante ac tincidunt. Phasellus sed ipsum sit amet nunc elementum egestas eu semper quam. Etiam tristique tincidunt pretium.

Aliquam lacinia leo eu nibh facilisis, sed sodales ligula lacinia. Nunc non pretium libero. Etiam eget mi turpis. Morbi nulla ex, blandit ac nisl eget, scelerisque vestibulum ante. Cras sollicitudin aliquet viverra. In interdum cursus risus, sed finibus lorem hendrerit quis. Phasellus mollis, tellus in imperdiet ultricies, massa justo venenatis risus, a posuere neque risus eget ex. Sed aliquam lorem enim, at ultrices dolor semper nec. In porta feugiat condimentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et vehicula nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque accumsan a velit in viverra. Cras urna mauris, pellentesque id aliquam eu, condimentum non lacus. Nam viverra leo eu neque placerat, porttitor imperdiet neque vehicula. Nullam eget diam non erat varius gravida eget eu dui. Nam eleifend nunc neque, vitae sollicitudin purus accumsan quis. Nullam pretium viverra risus, nec porta est placerat ac. Vestibulum tincidunt magna nec enim lobortis, ac vulputate justo sollicitudin. Suspendisse aliquam nunc non libero suscipit, a bibendum magna molestie. Mauris malesuada facilisis egestas. Phasellus eget fringilla turpis, eleifend pulvinar ex. Praesent dui nibh, accumsan ac vestibulum eget, fringilla ut augue. Nam quam eros, aliquam non nunc at, pretium cursus diam. Sed pharetra ante at risus dignissim cursus. Maecenas aliquet sapien a orci consectetur, a cursus libero accumsan.

Sed tristique consequat turpis luctus ultricies. Donec auctor ullamcorper neque. Etiam sed rutrum diam, tincidunt consectetur elit. Sed quis dolor congue, sodales ante placerat, laoreet libero. Vivamus vel ornare magna, et pretium sapien. Nulla aliquam mattis tortor, ac interdum mi fringilla in. Nam sit amet commodo tellus. Proin condimentum dignissim eros eget tempus.

Curabitur ut aliquam massa. Aliquam in metus aliquam, interdum tortor sit amet, varius augue. Maecenas egestas mauris nec nulla vestibulum euismod. Sed in orci consectetur, luctus dolor a, finibus diam. Integer congue risus vitae cursus varius. Suspendisse nec mollis quam, in porttitor lectus. Aliquam et laoreet orci. Sed tincidunt magna in mi vulputate iaculis. Aliquam sit amet velit ac urna laoreet varius a quis nunc. Nam sed pellentesque mauris. Morbi vel ligula at dolor dapibus tincidunt. Nullam sit amet interdum elit, vel commodo ipsum. Phasellus dapibus nisi vitae volutpat luctus. Ut accumsan pretium ligula, at malesuada risus maximus at.

Donec a est pellentesque libero congue elementum. Donec consectetur justo et sem maximus, ut condimentum nisl laoreet. Morbi ac enim in enim volutpat suscipit. Donec ultrices convallis orci eget accumsan. Ut bibendum ante et massa malesuada, a consequat dolor luctus. Curabitur nulla nisl, sodales nec dictum a, feugiat at ante. Nunc volutpat luctus ante ac tincidunt. Phasellus sed ipsum sit amet nunc elementum egestas eu semper quam. Etiam tristique tincidunt pretium.

Aliquam lacinia leo eu nibh facilisis, sed sodales ligula lacinia. Nunc non pretium libero. Etiam eget mi turpis. Morbi nulla ex, blandit ac nisl eget, scelerisque vestibulum ante. Cras sollicitudin aliquet viverra. In interdum cursus risus, sed finibus lorem hendrerit quis. Phasellus mollis, tellus in imperdiet ultricies, massa justo venenatis risus, a posuere neque risus eget ex. Sed aliquam lorem enim, at ultrices dolor semper nec. In porta feugiat condimentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et vehicula nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque accumsan a velit in viverra. Cras urna mauris, pellentesque id aliquam eu, condimentum non lacus. Nam viverra leo eu neque placerat, porttitor imperdiet neque vehicula. Nullam eget diam non erat varius gravida eget eu dui. Nam eleifend nunc neque, vitae sollicitudin purus accumsan quis. Nullam pretium viverra risus, nec porta est placerat ac. Vestibulum tincidunt magna nec enim lobortis, ac vulputate justo sollicitudin. Suspendisse aliquam nunc non libero suscipit, a bibendum magna molestie. Mauris malesuada facilisis egestas. Phasellus eget fringilla turpis, eleifend pulvinar ex. Praesent dui nibh, accumsan ac vestibulum eget, fringilla ut augue. Nam quam eros, aliquam non nunc at, pretium cursus diam. Sed pharetra ante at risus dignissim cursus. Maecenas aliquet sapien a orci consectetur, a cursus libero accumsan.

Sed tristique consequat turpis luctus ultricies. Donec auctor ullamcorper neque. Etiam sed rutrum diam, tincidunt consectetur elit. Sed quis dolor congue, sodales ante placerat, laoreet libero. Vivamus vel ornare magna, et pretium sapien. Nulla aliquam mattis tortor, ac interdum mi fringilla in. Nam sit amet commodo tellus. Proin condimentum dignissim eros eget tempus.

Curabitur ut aliquam massa. Aliquam in metus aliquam, interdum tortor sit amet, varius augue. Maecenas egestas mauris nec nulla vestibulum euismod. Sed in orci consectetur, luctus dolor a, finibus diam. Integer congue risus vitae cursus varius. Suspendisse nec mollis quam, in porttitor lectus. Aliquam et laoreet orci. Sed tincidunt magna in mi vulputate iaculis. Aliquam sit amet velit ac urna laoreet varius a quis nunc. Nam sed pellentesque mauris. Morbi vel ligula at dolor dapibus tincidunt. Nullam sit amet interdum elit, vel commodo ipsum. Phasellus dapibus nisi vitae volutpat luctus. Ut accumsan pretium ligula, at malesuada risus maximus at.

Donec a est pellentesque libero congue elementum. Donec consectetur justo et sem maximus, ut condimentum nisl laoreet. Morbi ac enim in enim volutpat suscipit. Donec ultrices convallis orci eget accumsan. Ut bibendum ante et massa malesuada, a consequat dolor luctus. Curabitur nulla nisl, sodales nec dictum a, feugiat at ante. Nunc volutpat luctus ante ac tincidunt. Phasellus sed ipsum sit amet nunc elementum egestas eu semper quam. Etiam tristique tincidunt pretium.

Aliquam lacinia leo eu nibh facilisis, sed sodales ligula lacinia. Nunc non pretium libero. Etiam eget mi turpis. Morbi nulla ex, blandit ac nisl eget, scelerisque vestibulum ante. Cras sollicitudin aliquet viverra. In interdum cursus risus, sed finibus lorem hendrerit quis. Phasellus mollis, tellus in imperdiet ultricies, massa justo venenatis risus, a posuere neque risus eget ex. Sed aliquam lorem enim, at ultrices dolor semper nec. In porta feugiat condimentum.
  </div>;
};

export default Home;
